### ISSUE TITLE
Error when announcing MosaicMetadataTransaction

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#113]
When announcing MetadataTransaction I got below server error

```
"stack":"TypeError: input.forEach is not a function\n    at Object.uint8ToHex (/Users/stevenliu/Documents/src/NEM/catapult-rest/catapult-sdk/_build/utils/convert.js:103:9)\n
```
Seems like the error is recent changes related as the metadata tx worked before.

It is also worth checking the other 2 metadata txs

**Comment by Vektrat** [comment]
the only change we made (in fact it was you :p) to metadata i think is this one:

- `signer` --> `signerPublicKey`

other than that, we changed the uint64 array when returning transcaction info

can you double check that you are sending the correct info? can you show the object here? are you sure it was working before?

**Comment by rg911** [comment]
Pretty positive worked before. 
I am running the rest from current master locally.  Full error log pasted here:
```
error: zmq confirmedAdded/SAKT3CKHCYIG5BBOPTSY2WXSVPBSLIA67AEOX4ND: error from zsocketinput.forEach is not a function {"stack":"TypeError: input.forEach is not a function\n
at Object.uint8ToHex (/Users/stevenliu/Documents/src/NEM/catapult-rest/catapult-sdk/_build/utils/convert.js:103:9)\n
at 4 (/Users/stevenliu/Documents/src/NEM/catapult-rest/rest/src/server/messageFormattingRules.js:28:39)\n
at /Users/stevenliu/Documents/src/NEM/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:92:37\n
at Array.forEach (<anonymous>)\n
at Object.format (/Users/stevenliu/Documents/src/NEM/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:76:23)\n
at /Users/stevenliu/Documents/src/NEM/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:80:33\n
at formattingRules.<computed> (/Users/stevenliu/Documents/src/NEM/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:65:59)\n
at /Users/stevenliu/Documents/src/NEM/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:92:37\n
at Array.forEach (<anonymous>)\n 
at Object.format (/Users/stevenliu/Documents/src/NEM/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:76:23)","timestamp":"2019-09-09T19:28:20.211Z"}
```

**Comment by Vektrat** [comment]
can you paste the transaction you are announcing?

**Comment by rg911** [comment]
Probably worth checking the ws handler. 

tx hash: `5d7767ab5e40d200015200e5` and `5d7769685e40d20001520153`
announced okay on C2, but got above error when retrieving from ws channel

**Comment by Vektrat** [comment]
yes the transaction gets announced, the error happens when feedback is returned to the client, i was asking about the tx json, but nm ^^

**Comment by rg911** [comment]
http://c2.nem.ninja:3000/transaction/5d7767ab5e40d200015200e5
