### ISSUE TITLE
Not receiving ws messages for metadata transaction 

### ISSUE THREAD

**Issue by rg911** [nemtech/catapult-rest#155]
Noticed this happens after `value` format changed

**Comment by fboucquez** [comment]
I'm seeing this error in the catpult-rest logs after pulling the last master, probably related?

```
error: zmq confirmedAdded/SDKBUEJJ4VV2RTAR4BLWXYTUSTNZ5HHFDMRKJJY2: error from zsocketinput.forEach is not a function {"stack":"TypeError: input.forEach is not a function
    at Object.uint8ToHex (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/utils/convert.js:103:9)
    at 4 (/home/fernando/develop/workspace-nem/catapult-rest/rest/_build/server/messageFormattingRules.js:28:39)
    at /home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:92:37
    at Array.forEach (<anonymous>)
    at Object.format (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:76:23)
    at /home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:80:33
    at formattingRules.<computed> (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:65:59)
    at /home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:92:37
    at Array.forEach (<anonymous>)
    at Object.format (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/utils/schemaFormatter.js:76:23)","timestamp":"2019-10-07T10:47:02.940Z"}
```

**Comment by Vektrat** [comment]
yep most likely related, i wanted to take a look at this when c2 was up, but it still isnt :/

**Comment by Vektrat** [comment]
i believe i think what may be happening here, i'll try to fix it with a guess without c2
