### ISSUE TITLE
aggregate.js listener error after announcing transaction.

### ISSUE THREAD

**Issue by fboucquez** [nemtech/catapult-rest#207]
The transaction that raises the error is:
````
{ 
   "transaction":{ 
      "deadline":"114869328626",
      "maxFee":"1000000",
      "network":144,
      "transactions":[ 
         { 
            "transaction":{ 
               "network":144,
               "scopedMetadataKey":"a6f7",
               "signerPublicKey":"42CEE8635A8BF33094AD92C72EC02A2E1F5085A76FDD94D24093B37CBFA6764A",
               "targetPublicKey":"42CEE8635A8BF33094AD92C72EC02A2E1F5085A76FDD94D24093B37CBFA6764A",
               "type":16708,
               "value":"546865206f726967696e616c206d657373616765",
               "valueSize":20,
               "valueSizeDelta":20,
               "version":1
            }
         }
      ],
      "transactionsHash":"4E989536AA4E0914B177D48FDE628526D43D25B3AFE4637743D2ADB5CE9385C4",
      "type":16705,
      "version":1
   }
}
````
The error:

````
error: zmq confirmedAdded/SDKBUEJJ4VV2RTAR4BLWXYTUSTNZ5HHFDMRKJJY2: error from zsocketCannot read property 'length' of undefined {"stack":"TypeError: Cannot read property 'length' of undefined
    at BufferContainer.nextBufferInPlace (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/parser/BinaryParser.js:87:14)
    at BufferContainer.nextBuffer (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/parser/BinaryParser.js:82:15)
    at BinaryParser.buffer (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/parser/BinaryParser.js:167:23)
    at Object.deserialize (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/plugins/aggregate.js:142:14)
    at codecs.forEach.codec (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/modelBinary/ModelCodecBuilder.js:121:34)
    at Array.forEach (<anonymous>)\n    at Object.deserialize (/home/fernando/develop/workspace-nem/catapult-rest/catapult-sdk/_build/modelBinary/ModelCodecBuilder.js:120:12)
    at exports.Socket.<anonymous> (/home/fernando/develop/workspace-nem/catapult-rest/rest/_build/connection/MessageChannelBuilder.js:55:29)
    at exports.Socket.emit (events.js:198:13)\n    at exports.Socket.EventEmitter.emit (domain.js:448:20)","timestamp":"2019-11-21T09:44:33.855Z"}

````

**Comment by Vektrat** [comment]
this is happening on a branch

**Comment by fboucquez** [comment]
The master fails due to the missing aggregate padding after transactions. This is the next error after paddings are there for some aggregate.

**Comment by fboucquez** [comment]
Another transaction failing:

````
{ 
   "transaction":{ 
      "deadline":"114886303294",
      "maxFee":"1000000",
      "network":144,
      "transactions":[ 
         { 
            "transaction":{ 
               "network":144,
               "scopedMetadataKey":"49631",
               "signerPublicKey":"D38600B233CEA0A089D4A4A2FC0188A5579A3EA0057B0C4EEF8A94F3AD2C1273",
               "targetNamespaceId":"d2e1f9cc24e971e3",
               "targetPublicKey":"D38600B233CEA0A089D4A4A2FC0188A5579A3EA0057B0C4EEF8A94F3AD2C1273",
               "type":17220,
               "value":"546865206f726967696e616c206d657373616765",
               "valueSize":20,
               "valueSizeDelta":20,
               "version":1
            }
         }
      ],
      "transactionsHash":"271993F7BFD4C40FB7029D83738983A9EF3CAA00B9FE40B6A88510820456F69D",
      "type":16705,
      "version":1
   }
}
````

**Comment by fboucquez** [comment]
I've just push a fix to the task/add-padding-after-inner-aggregate-transactions branch

`parser.buffer(paddingSize);` breaks when paddingSize is 0

https://github.com/nemtech/catapult-rest/pull/205/commits/0b22cce927a96daa781421e602df4a7533a0ea58
